dist: focal
language: node_js
node_js:
  - 16
env:
  - tf_version=1.0.10
cache: npm
script:
  - wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
  - unzip terraform_"$tf_version"_linux_amd64.zip
  - sudo mv terraform /usr/local/bin/
  - rm terraform_"$tf_version"_linux_amd64.zip
  - pip3 install awscli
  - cd ci && bash ci.sh
